"""
hypothesis_store.py — Persistent, deduplicated hypothesis memory.

Hypotheses are structured insights generated by the reflection system.
Unlike raw reflections (which are ephemeral), hypotheses persist across
sessions, accumulate evidence from multiple experiments, and can be
promoted into constitution amendments when confirmed.

Key design decisions:
  - Novelty gate: Jaccard similarity on word tokens before accepting any new hypothesis
  - Evidence tracking: experiments that support or refute each hypothesis
  - Confidence decay: stale hypotheses lose weight over time
  - Promotion path: active → confirmed (≥3 supporting) → archived

Storage: .agent/hypotheses.jsonl (append-log, compacted on save)
"""

from __future__ import annotations

import hashlib
import json
import logging
import pathlib
import time
import re
from dataclasses import dataclass, field, asdict
from typing import Literal

logger = logging.getLogger(__name__)

HYPOTHESES_PATH = pathlib.Path(".agent/hypotheses.jsonl")

HypothesisStatus = Literal["active", "confirmed", "refuted", "archived"]


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class Hypothesis:
    id: str
    text: str
    category: str                     # "strategy" | "metric" | "tool_use" | "general"
    evidence_for: list[str]           # experiment IDs that support this
    evidence_against: list[str]       # experiment IDs that refute this
    confidence: float                 # 0.0–1.0
    created_at: float
    last_tested: float
    status: HypothesisStatus
    source: str = "reflection"        # "reflection" | "manual" | "meta_eval"

    @classmethod
    def from_dict(cls, d: dict) -> "Hypothesis":
        return cls(
            id=d["id"],
            text=d["text"],
            category=d.get("category", "general"),
            evidence_for=d.get("evidence_for", []),
            evidence_against=d.get("evidence_against", []),
            confidence=d.get("confidence", 0.5),
            created_at=d.get("created_at", time.time()),
            last_tested=d.get("last_tested", time.time()),
            status=d.get("status", "active"),
            source=d.get("source", "reflection"),
        )

    def to_dict(self) -> dict:
        return asdict(self)

    @property
    def net_evidence(self) -> int:
        return len(self.evidence_for) - len(self.evidence_against)

    @property
    def is_confirmed(self) -> bool:
        return len(self.evidence_for) >= 3 and self.net_evidence >= 2


# ---------------------------------------------------------------------------
# Novelty scoring
# ---------------------------------------------------------------------------

def _tokenize(text: str) -> set[str]:
    """Extract meaningful word tokens for similarity comparison."""
    # Lowercase, split on non-word chars, filter short/common words
    stopwords = {"the", "a", "an", "is", "are", "was", "were", "be", "been",
                 "have", "has", "do", "does", "will", "would", "could", "should",
                 "when", "if", "and", "or", "not", "to", "of", "in", "on", "at",
                 "it", "its", "that", "this", "with", "for", "from", "by"}
    tokens = set(re.findall(r'\b[a-z]{3,}\b', text.lower()))
    return tokens - stopwords


def jaccard_similarity(text_a: str, text_b: str) -> float:
    """Jaccard similarity between two texts based on word tokens."""
    a = _tokenize(text_a)
    b = _tokenize(text_b)
    if not a and not b:
        return 1.0
    if not a or not b:
        return 0.0
    return len(a & b) / len(a | b)


def _make_id(text: str) -> str:
    """Stable short ID from text content."""
    return "hyp_" + hashlib.md5(text.strip().lower().encode()).hexdigest()[:8]


# ---------------------------------------------------------------------------
# Main store
# ---------------------------------------------------------------------------

class HypothesisStore:
    """In-memory store backed by a JSONL file.

    Usage:
        store = HypothesisStore()
        store.load()
        if store.add_if_novel("Fewer tool calls → higher scores", "strategy"):
            print("New hypothesis recorded!")
        store.save()
    """

    NOVELTY_THRESHOLD = 0.65    # above this → too similar to existing, skip
    CONFIDENCE_DECAY  = 0.05    # per session if hypothesis not tested
    CONFIRM_THRESHOLD = 3       # min supporting experiments to confirm
    STALE_SESSIONS    = 5       # sessions without testing before decay

    def __init__(self, path: pathlib.Path | None = None):
        self.path = path or HYPOTHESES_PATH
        self._hypotheses: dict[str, Hypothesis] = {}   # id → Hypothesis

    # ------------------------------------------------------------------ I/O

    def load(self) -> "HypothesisStore":
        """Load from disk. Returns self for chaining."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        if not self.path.exists():
            return self

        with open(self.path, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    d = json.loads(line)
                    h = Hypothesis.from_dict(d)
                    self._hypotheses[h.id] = h
                except (json.JSONDecodeError, KeyError) as e:
                    logger.debug("Skipping malformed hypothesis entry: %s", e)

        logger.info("HypothesisStore: loaded %d hypotheses", len(self._hypotheses))
        return self

    def save(self) -> None:
        """Compact-save all hypotheses to disk (full rewrite)."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.path, "w", encoding="utf-8") as f:
            for h in self._hypotheses.values():
                f.write(json.dumps(h.to_dict()) + "\n")

    # ------------------------------------------------------ Core operations

    def add_if_novel(
        self,
        text: str,
        category: str = "general",
        source: str = "reflection",
        confidence: float = 0.6,
    ) -> bool:
        """Add a hypothesis only if it is sufficiently novel.

        Returns True if the hypothesis was added, False if it was rejected
        as a duplicate of an existing hypothesis.
        """
        # Check novelty against all active hypotheses
        for existing in self._hypotheses.values():
            if existing.status in ("archived", "refuted"):
                continue
            sim = jaccard_similarity(text, existing.text)
            if sim >= self.NOVELTY_THRESHOLD:
                logger.debug(
                    "Hypothesis rejected (similarity=%.2f to '%s'): '%s'",
                    sim, existing.id, text[:60]
                )
                return False

        hyp = Hypothesis(
            id=_make_id(text),
            text=text,
            category=category,
            evidence_for=[],
            evidence_against=[],
            confidence=confidence,
            created_at=time.time(),
            last_tested=time.time(),
            status="active",
            source=source,
        )
        # Handle ID collision (very unlikely but safe)
        while hyp.id in self._hypotheses:
            hyp.id += "_"

        self._hypotheses[hyp.id] = hyp
        logger.info("New hypothesis recorded [%s]: %s", hyp.id, text[:80])
        return True

    def record_evidence(
        self,
        experiment_id: str,
        supports: list[str] | None = None,
        refutes: list[str] | None = None,
    ) -> None:
        """Record an experiment as evidence for/against specific hypotheses.

        Args:
            experiment_id: e.g. "exp_1068"
            supports: hypothesis IDs this experiment supports
            refutes:  hypothesis IDs this experiment refutes
        """
        for hid in (supports or []):
            if hid in self._hypotheses:
                h = self._hypotheses[hid]
                if experiment_id not in h.evidence_for:
                    h.evidence_for.append(experiment_id)
                h.last_tested = time.time()
                self._check_promotion(h)

        for hid in (refutes or []):
            if hid in self._hypotheses:
                h = self._hypotheses[hid]
                if experiment_id not in h.evidence_against:
                    h.evidence_against.append(experiment_id)
                h.last_tested = time.time()
                if len(h.evidence_against) >= 2 and h.net_evidence < 0:
                    h.status = "refuted"
                    logger.info("Hypothesis refuted [%s]: %s", hid, h.text[:60])

    def decay_stale(self, sessions_elapsed: int = 1) -> int:
        """Apply confidence decay to hypotheses not tested recently.

        Returns number of hypotheses archived.
        """
        archived = 0
        for h in self._hypotheses.values():
            if h.status != "active":
                continue
            days_stale = (time.time() - h.last_tested) / 86400
            if days_stale > self.STALE_SESSIONS:
                h.confidence = max(0.1, h.confidence - self.CONFIDENCE_DECAY * sessions_elapsed)
                if h.confidence <= 0.1:
                    h.status = "archived"
                    archived += 1
                    logger.info("Hypothesis archived (stale) [%s]", h.id)
        return archived

    def get_confirmed(self) -> list[Hypothesis]:
        """Return all confirmed hypotheses ready for constitution amendment."""
        return [h for h in self._hypotheses.values() if h.status == "confirmed"]

    def get_active(self) -> list[Hypothesis]:
        """Return all active (unconfirmed, non-refuted) hypotheses."""
        return [h for h in self._hypotheses.values() if h.status == "active"]

    def summary(self) -> dict:
        """Return count summary for display."""
        counts: dict[str, int] = {}
        for h in self._hypotheses.values():
            counts[h.status] = counts.get(h.status, 0) + 1
        return counts

    def format_for_prompt(self, max_items: int = 5) -> str:
        """Format confirmed + high-confidence hypotheses for inclusion in LLM prompts."""
        candidates = sorted(
            [h for h in self._hypotheses.values() if h.status in ("active", "confirmed")],
            key=lambda h: (h.status == "confirmed", h.confidence, len(h.evidence_for)),
            reverse=True,
        )[:max_items]

        if not candidates:
            return ""

        lines = ["Previously confirmed insights:"]
        for h in candidates:
            evidence = f"({len(h.evidence_for)} experiments)"
            marker = "✓" if h.status == "confirmed" else "~"
            lines.append(f"  {marker} {h.text} {evidence}")
        return "\n".join(lines)

    # --------------------------------------------------------------- Private

    def _check_promotion(self, h: Hypothesis) -> None:
        if h.status == "active" and h.is_confirmed:
            h.status = "confirmed"
            h.confidence = min(1.0, h.confidence + 0.1)
            logger.info("Hypothesis CONFIRMED [%s]: %s", h.id, h.text[:60])


# ---------------------------------------------------------------------------
# Module-level singleton convenience
# ---------------------------------------------------------------------------

_store: HypothesisStore | None = None


def get_store() -> HypothesisStore:
    """Return the module-level store, loading from disk if needed."""
    global _store
    if _store is None:
        _store = HypothesisStore()
        _store.load()
    return _store


def add_hypothesis(text: str, category: str = "general", **kwargs) -> bool:
    """Convenience wrapper: add hypothesis to the module-level store."""
    return get_store().add_if_novel(text, category, **kwargs)


def save_hypotheses() -> None:
    """Save the module-level store to disk."""
    if _store is not None:
        _store.save()


if __name__ == "__main__":
    """Quick smoke test."""
    import logging
    logging.basicConfig(level=logging.INFO, format="%(message)s")

    store = HypothesisStore(pathlib.Path(".agent/test_hypotheses.jsonl"))

    # Test novelty gating
    added = store.add_if_novel("Fewer tool calls leads to higher overall task scores", "strategy")
    print(f"Added first: {added}")  # True

    added = store.add_if_novel("Using fewer tools results in better task performance scores", "strategy")
    print(f"Added duplicate: {added}")  # False (too similar)

    added = store.add_if_novel("Tasks completed in fewer steps tend to have higher constitutional alignment", "strategy")
    print(f"Added similar: {added}")  # Might be False depending on threshold

    added = store.add_if_novel("The agent performs worse when curiosity drive weight exceeds 0.2", "metric")
    print(f"Added different: {added}")  # True

    # Test evidence
    ids = list(store._hypotheses.keys())
    if ids:
        store.record_evidence("exp_1001", supports=[ids[0]])
        store.record_evidence("exp_1002", supports=[ids[0]])
        store.record_evidence("exp_1003", supports=[ids[0]])
        print(f"Confirmed: {store._hypotheses[ids[0]].status}")  # confirmed

    print(f"\nSummary: {store.summary()}")
    print(f"\nFor prompt:\n{store.format_for_prompt()}")

    # Cleanup test file
    pathlib.Path(".agent/test_hypotheses.jsonl").unlink(missing_ok=True)
